


CREATE TABLE admin2 ( -- 管理员表
	id INT PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(32) NOT NULL UNIQUE, 
	pwd VARCHAR(32) NOT NULL DEFAULT '') 
	CHARACTER SET utf8; 
	
DROP TABLE admin2;

SELECT * FROM admin2;
